### ISSUE TITLE
Remove memoffset from dependencies

### ISSUE THREAD

**Issue by Nugine** [Manishearth/triomphe#32]
I searched the usage of memoffset. 
<https://github.com/Manishearth/triomphe/search?q=offset_of>
I find that there are only three `offset_of!` and the layout of data structures are stable. So it's easy to replace the macro with simple constants.

**Comment by Manishearth** [comment]
Rust layout is absolutely not stable

Though there may be stdlib builtins for offset now

**Comment by Nugine** [comment]
ArcInner and HeaderSlice have the attribute `repr(C)` so their layouts are stable.

https://github.com/Manishearth/triomphe/blob/b6a83f62662bee19f734b8a43bacfac8ad2d9bd6/src/arc.rs#L36
https://github.com/Manishearth/triomphe/blob/df0434a81b9a5121f8510d3c0c4d9ec4d13a7ae3/src/header.rs#L15

**Comment by Manishearth** [comment]
Ah. I would still like to not have to rely on hardcoded constants here

But I think stdlib has ptr_addr_of if you want to get rid of the dep

**Comment by Nugine** [comment]
ptr::addr_of{_mut} are better but they are added since Rust 1.51.0. Do you have a MSRV policy?

**Comment by Manishearth** [comment]
Not really no
