### ISSUE TITLE
Arc::from_raw requires Sized

### ISSUE THREAD

**Issue by stepancheg** [Manishearth/triomphe#56]
`Arc::into_raw` does not require Sized, but `Arc::from_raw` does. Must be a mistake.

Edit: I missed todo

https://github.com/Manishearth/triomphe/blob/0c63099082ba155885c304b3b42e424b676da8ee/src/arc.rs#L81

However, for now `Arc` can have an operation like `Arc::from_raw_slice`. Practically many unsized types are just slices.

**Comment by Manishearth** [comment]
Seems like a good idea
