### ISSUE TITLE
`T: 'static` bound on `ArcBorrow::with_arc` probably unnecessarily restrictive

### ISSUE THREAD

**Issue by steffahn** [Manishearth/triomphe#79]
I feel like the bound might be unnecessary and thus overly restrictive. I'm writing this down as an issue first to allow others to look at this, too, (or for myself to take a second look) before contributing a change (removing the `T: 'static` line here).

https://github.com/Manishearth/triomphe/blob/31f59f20d40fef39235c64633a3fd81e3b56e381/src/arc_borrow.rs#L66-L69

**Comment by Manishearth** [comment]
Yeah it's probably unnecessary
