### ISSUE TITLE
Specify an MSRV policy

### ISSUE THREAD

**Issue by tertsdiepraam** [Manishearth/triomphe#90]
Hi! We depend on this library in [`domain`](https://github.com/nlnetlabs/domain/) transitively via `moka` and just got bit by new requirement that rust 1.76 or later should be used. This is fine of course, but I wanted to ask if you could specify some MSRV policy or provide the `rust-version` key in `Cargo.toml`, which will help prevent issues like this once the MSRV-dependent resolver lands.

**Comment by Manishearth** [comment]
Sounds good, I'll add the `rust-version` key. I don't really plan on maintaining any MSRV between semver-compat releases, but it doesn't hurt to have the metadata in the Cargo.toml!

**Comment by tertsdiepraam** [comment]
Not wanting to maintain a policy is very understandable. Thank you!
