### ISSUE TITLE
Repository rolled back?

### ISSUE THREAD

**Issue by arthurprs** [Manishearth/triomphe#99]
I was trying to upgrade my dependency to use #95 and #96 but noticed the newly released 0.1.13 doesn't contain them. They're not in `master` even. Do you know what's up?

**Comment by Manishearth** [comment]
I suspect what happened was that I saw a 0.1.13 on master already and published it, assuming I had made the release commit recently and just forgotten to publish. I can bring it back to the right state in a day or two.

**Comment by Manishearth** [comment]
Fixed

**Comment by arthurprs** [comment]
Thank you. I see the crates.io release and https://github.com/Manishearth/triomphe/tree/v0.1.14 but AFAICT master is still behind.

**Comment by Manishearth** [comment]
Ah, I need to push. Will do

**Comment by Manishearth** [comment]
done
